import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {Outfit} from 'next/font/google'

const Outfit = Outfit({subsets:['latin']});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className= {Outfit.className}
      >
        {children}
      </body>
    </html>
  );
}
